name: oracle_cli
description: >-
  A cli application that provides oracles for solo roleplaying, 
  or GM-less play.d
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

executables:
  doracle:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  dart_clipboard: ^0.3.0
  interact: ^2.2.0
  path: ^1.8.3
  yaml: ^3.1.2
